export const roofingSynonyms: string[] = [
  "roofing",
  "shingles",
  "roof repair",
  "reroof",
  "roof replacement",
  "roof work",
  "roof install",
  "roofing contractor",
  "roofing company",
  "roof contractor",
  "new roof",
  "re-roofing",
  "roofing materials",
  "roof shingles",
  "metal roof",
  "standing seam",
  "roof tile",
  "tile roof",
  "cedar shake",
  "wood roof",
  "slate roof",
  "synthetic roof",
  "roof leak",
  "roof inspection",
  "roof ventilation",
  "roof flashing",
  "roof underlayment",
  "roof gutters",
  "roof chimney",
];
