import { createFileRoute } from "@tanstack/react-router";
import { SiteNav } from "@/components/SiteNav";
import { SiteFooter } from "@/components/SiteFooter";
import { FileText } from "lucide-react";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SiteNav />
      <main className="container-x py-20">
        <div className="max-w-3xl mx-auto">
          <div className="w-14 h-14 rounded-2xl bg-accent/10 flex items-center justify-center mx-auto mb-6">
            <FileText className="h-7 w-7 text-accent" />
          </div>
          <h1 className="font-display text-3xl md:text-4xl font-bold text-ink mb-4 text-center">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground text-center mb-12">
            Last updated: July 20, 2026
          </p>

          <div className="prose prose-lg max-w-none text-left">
            <p>Please read these terms carefully before using CostReno.</p>

            <h2>1. Acceptance of terms</h2>
            <p>
              By accessing or using CostReno (the "Service"), you agree to be bound by these Terms
              of Service. If you do not agree, do not use the Service.
            </p>

            <h2>2. Description of the service</h2>
            <p>
              CostReno provides general cost estimation tools, contractor quote analysis, and
              insurance claim guidance content for informational purposes. CostReno is not a
              contractor, insurer, public adjuster, law firm, or financial advisor, and does not
              provide legal, insurance, or financial advice.
            </p>

            <h2>3. Estimates are not guarantees</h2>
            <p>
              All cost estimates, ranges, and comparisons generated by the Service are general
              guidance based on regional data and user-provided information. They are not a
              guaranteed quote, appraisal, or promise of actual project cost. Actual costs may vary
              significantly based on factors the Service cannot fully account for. You should obtain
              a written quote from a licensed, insured contractor before making financial decisions.
            </p>

            <h2>4. AI-generated content</h2>
            <p>
              Some features use artificial intelligence to analyze photos, quotes, or documents you
              upload. AI-generated analysis may contain errors or omissions. You are responsible for
              independently verifying any conclusions before relying on them, particularly for
              insurance claim or legal matters.
            </p>

            <h2>5. Not insurance or legal advice</h2>
            <p>
              Any content related to insurance claims, coverage, or contractor disputes is general
              educational information only. It is not a substitute for advice from a licensed
              insurance professional, public adjuster, or attorney. For any specific claim or
              dispute, consult a qualified professional.
            </p>

            <h2>6. User-submitted content and license</h2>
            <p>
              By uploading photos, quotes, or documents, you confirm you have the right to submit
              that content. You grant CostReno a non-exclusive, worldwide, royalty-free license to
              use, process, and analyze that content to provide the requested service and to train
              and improve our estimation models and AI systems, in accordance with our Privacy
              Policy. You are responsible for removing any sensitive personal information you do not
              wish to share beyond what is necessary for the analysis.
            </p>

            <h2>7. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service for any unlawful purpose</li>
              <li>Upload content that infringes on the rights of others</li>
              <li>
                Attempt to reverse-engineer, scrape, or misuse the Service's underlying tools or
                data
              </li>
              <li>
                Misrepresent estimates generated by the Service as guaranteed pricing to a third
                party
              </li>
            </ul>

            <h2>8. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, CostReno and its operators are not liable for
              any indirect, incidental, or consequential damages arising from your use of the
              Service, including decisions made based on estimates, comparisons, or content
              provided. The Service is provided "as is" without warranties of any kind.
            </p>

            <h2>9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless CostReno from claims arising out of your
              misuse of the Service or violation of these terms.
            </p>

            <h2>10. Changes to the service and terms</h2>
            <p>
              We may modify or discontinue features of the Service at any time. We may update these
              terms, and continued use after changes constitutes acceptance of the revised terms.
            </p>

            <h2>11. Governing law</h2>
            <p>
              These terms are governed by the laws of the State of Delaware, United States, without
              regard to conflict of law principles, and any disputes will be resolved in the state
              or federal courts located in Delaware.
            </p>

            <h2>12. Contact</h2>
            <p>Questions about these terms can be directed to legal@costreno.com.</p>
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
