import { createFileRoute } from "@tanstack/react-router";
import { SiteNav } from "@/components/SiteNav";
import { SiteFooter } from "@/components/SiteFooter";
import { FileText } from "lucide-react";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SiteNav />
      <main className="container-x py-20">
        <div className="max-w-3xl mx-auto">
          <div className="w-14 h-14 rounded-2xl bg-accent/10 flex items-center justify-center mx-auto mb-6">
            <FileText className="h-7 w-7 text-accent" />
          </div>
          <h1 className="font-display text-3xl md:text-4xl font-bold text-ink mb-4 text-center">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground text-center mb-12">
            Last updated: July 20, 2026
          </p>

          <div className="prose prose-lg max-w-none text-left">
            <p>
              Please read these Terms of Service ("Terms") carefully before using CostReno
              ("CostReno," "we," "our," or "us"). By accessing or using our website and services
              (the "Service"), you agree to these Terms. If you do not agree, please do not use the
              Service.
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using CostReno, you agree to be bound by these Terms and our Privacy
              Policy.
            </p>

            <h2>2. Description of the Service</h2>
            <p>
              CostReno provides AI-powered renovation cost estimation tools, contractor quote
              analysis, insurance claim guidance, educational content, and related services.
            </p>
            <p>
              The Service is designed to help homeowners better understand renovation projects and
              contractor quotes. CostReno is <strong>not</strong>:
            </p>
            <ul>
              <li>a licensed contractor</li>
              <li>an architect or engineer</li>
              <li>a public adjuster</li>
              <li>an insurance company</li>
              <li>a law firm</li>
              <li>a financial advisor</li>
            </ul>
            <p>
              Use of the Service does <strong>not</strong> create any professional, fiduciary,
              contractor-client, attorney-client, engineer-client, insurance advisor, or similar
              relationship between you and CostReno.
            </p>

            <h2>3. Estimates Are Not Guarantees</h2>
            <p>
              All estimates, price ranges, recommendations, comparisons, and timelines generated by
              CostReno are informational only.
            </p>
            <p>
              They are based on regional pricing data, historical information, AI analysis, and
              user-provided inputs. Actual project costs may differ due to factors including:
            </p>
            <ul>
              <li>labor availability</li>
              <li>material pricing</li>
              <li>contractor pricing</li>
              <li>permits</li>
              <li>property conditions</li>
              <li>project complexity</li>
              <li>regional market conditions</li>
            </ul>
            <p>
              Nothing generated by the Service should be considered a guaranteed quote, appraisal,
              or promise of actual project cost. Always obtain written quotes from licensed
              contractors before making financial decisions.
            </p>

            <h2>4. AI-Generated Analysis</h2>
            <p>
              Some features use artificial intelligence to analyze photos, contractor quotes,
              invoices, insurance documents, or other files you upload.
            </p>
            <p>
              AI-generated results may contain inaccuracies, omissions, or incorrect
              interpretations, including but not limited to:
            </p>
            <ul>
              <li>material identification</li>
              <li>room dimensions</li>
              <li>project scope</li>
              <li>pricing assumptions</li>
              <li>contractor quote analysis</li>
            </ul>
            <p>
              Quote reviews are intended to help identify potential missing scope items, pricing
              differences, or areas that may deserve further review. They should{" "}
              <strong>not</strong> be interpreted as confirmation that a contractor's quote is
              accurate, inaccurate, fair, unfair, complete, or incomplete. You are solely
              responsible for independently verifying all AI-generated information before relying on
              it.
            </p>

            <h2>5. No Legal, Insurance, or Professional Advice</h2>
            <p>
              Content provided by CostReno is for general educational and informational purposes
              only. Nothing on the Service constitutes legal advice, insurance advice, engineering
              advice, architectural advice, financial advice, or professional contracting advice. If
              you require professional assistance, consult a qualified licensed professional.
            </p>

            <h2>6. User Content</h2>
            <p>
              You retain ownership of all photos, contractor quotes, documents, and other content
              you upload. By uploading content, you confirm that you have the legal right to submit
              it.
            </p>
            <p>
              You grant CostReno a non-exclusive, worldwide, royalty-free license to process,
              analyze, store, and display your content solely for providing the requested Service,
              improving the accuracy of our estimation models, improving our AI systems, maintaining
              and securing the Service, and where practical, using anonymized and aggregated data to
              improve our products. We do <strong>not</strong> sell your uploaded documents. We
              recommend removing unnecessary personal or sensitive information before uploading
              documents.
            </p>

            <h2>7. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>use the Service for unlawful purposes</li>
              <li>upload content you do not own or have permission to use</li>
              <li>upload malicious software or harmful files</li>
              <li>attempt to reverse engineer, scrape, or copy the Service</li>
              <li>interfere with the security or operation of the Service</li>
              <li>misrepresent CostReno estimates as guaranteed pricing</li>
              <li>use the Service to violate the rights of others</li>
            </ul>

            <h2>8. Intellectual Property</h2>
            <p>
              The CostReno website, software, algorithms, AI models, designs, branding, logos,
              databases, text, graphics, and other content are owned by CostReno or its licensors
              and are protected by applicable intellectual property laws. Except as expressly
              permitted, you may not copy, reproduce, distribute, modify, or create derivative works
              from any part of the Service.
            </p>

            <h2>9. Availability of Service</h2>
            <p>
              We continually improve the Service. We may modify, suspend, discontinue, or remove
              features at any time without notice. We do not guarantee uninterrupted, secure, or
              error-free operation of the Service.
            </p>

            <h2>10. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, CostReno and its owners, employees,
              affiliates, and partners shall not be liable for any indirect, incidental,
              consequential, special, exemplary, or punitive damages arising from your use of the
              Service.
            </p>
            <p>
              You acknowledge that renovation projects, contractor selection, insurance claims, and
              financial decisions involve inherent risks. You are solely responsible for any
              decisions made based on information provided by the Service. The Service is provided{" "}
              <strong>"AS IS"</strong> and <strong>"AS AVAILABLE"</strong> without warranties of any
              kind, express or implied.
            </p>

            <h2>11. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless CostReno and its affiliates from any
              claims, damages, liabilities, losses, costs, or expenses arising from your use of the
              Service, your uploaded content, your violation of these Terms, or your violation of
              applicable law or third-party rights.
            </p>

            <h2>12. Termination</h2>
            <p>
              We reserve the right to suspend or terminate access to the Service at any time if we
              reasonably believe you have violated these Terms or used the Service in a harmful or
              unlawful manner.
            </p>

            <h2>13. Changes to These Terms</h2>
            <p>
              We may update these Terms periodically. The updated version will be posted on this
              page with a revised "Last updated" date. Your continued use of the Service after
              changes become effective constitutes acceptance of the revised Terms.
            </p>

            <h2>14. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Delaware, United States, without
              regard to conflict of law principles. Any legal action relating to these Terms or the
              Service shall be brought exclusively in the state or federal courts located in
              Delaware.
            </p>

            <h2>15. Age Requirement</h2>
            <p>
              You must be at least <strong>18 years old</strong>, or have permission from a parent
              or legal guardian, to use the Service.
            </p>

            <h2>16. Contact</h2>
            <p>If you have questions about these Terms, please contact:</p>
            <p>
              <strong>Email:</strong> <a href="mailto:legal@costreno.com">legal@costreno.com</a>
            </p>
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
