/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuoteAnalyzerRouteImport } from './routes/quote-analyzer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as KitchenRemodelCostRouteImport } from './routes/kitchen-remodel-cost'
import { Route as InsuranceClaimsRouteImport } from './routes/insurance-claims'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareQuotesRouteImport } from './routes/compare-quotes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProjectSlugRouteImport } from './routes/$projectSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesWindowReplacementRouteImport } from './routes/guides/window-replacement'
import { Route as GuidesRoofReplacementRouteImport } from './routes/guides/roof-replacement'
import { Route as GuidesMetalVsAsphaltRoofRouteImport } from './routes/guides/metal-vs-asphalt-roof'
import { Route as GuidesKitchenRemodelRouteImport } from './routes/guides/kitchen-remodel'
import { Route as GuidesInflatedQuoteSignsRouteImport } from './routes/guides/inflated-quote-signs'
import { Route as GuidesHvacInstallationRouteImport } from './routes/guides/hvac-installation'
import { Route as GuidesFlooringRouteImport } from './routes/guides/flooring'
import { Route as GuidesBathroomRemodelRouteImport } from './routes/guides/bathroom-remodel'
import { Route as StateCityCategoryRouteImport } from './routes/$state/$city/$category'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteAnalyzerRoute = QuoteAnalyzerRouteImport.update({
  id: '/quote-analyzer',
  path: '/quote-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRemodelCostRoute = KitchenRemodelCostRouteImport.update({
  id: '/kitchen-remodel-cost',
  path: '/kitchen-remodel-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceClaimsRoute = InsuranceClaimsRouteImport.update({
  id: '/insurance-claims',
  path: '/insurance-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareQuotesRoute = CompareQuotesRouteImport.update({
  id: '/compare-quotes',
  path: '/compare-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesWindowReplacementRoute = GuidesWindowReplacementRouteImport.update({
  id: '/guides/window-replacement',
  path: '/guides/window-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoofReplacementRoute = GuidesRoofReplacementRouteImport.update({
  id: '/guides/roof-replacement',
  path: '/guides/roof-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesMetalVsAsphaltRoofRoute =
  GuidesMetalVsAsphaltRoofRouteImport.update({
    id: '/guides/metal-vs-asphalt-roof',
    path: '/guides/metal-vs-asphalt-roof',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesKitchenRemodelRoute = GuidesKitchenRemodelRouteImport.update({
  id: '/guides/kitchen-remodel',
  path: '/guides/kitchen-remodel',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesInflatedQuoteSignsRoute =
  GuidesInflatedQuoteSignsRouteImport.update({
    id: '/guides/inflated-quote-signs',
    path: '/guides/inflated-quote-signs',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHvacInstallationRoute = GuidesHvacInstallationRouteImport.update({
  id: '/guides/hvac-installation',
  path: '/guides/hvac-installation',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFlooringRoute = GuidesFlooringRouteImport.update({
  id: '/guides/flooring',
  path: '/guides/flooring',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesBathroomRemodelRoute = GuidesBathroomRemodelRouteImport.update({
  id: '/guides/bathroom-remodel',
  path: '/guides/bathroom-remodel',
  getParentRoute: () => rootRouteImport,
} as any)
const StateCityCategoryRoute = StateCityCategoryRouteImport.update({
  id: '/$state/$city/$category',
  path: '/$state/$city/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRoute
  '/about': typeof AboutRoute
  '/compare-quotes': typeof CompareQuotesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/estimate': typeof EstimateRoute
  '/insurance-claims': typeof InsuranceClaimsRoute
  '/kitchen-remodel-cost': typeof KitchenRemodelCostRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/quote-analyzer': typeof QuoteAnalyzerRoute
  '/terms': typeof TermsRoute
  '/guides/bathroom-remodel': typeof GuidesBathroomRemodelRoute
  '/guides/flooring': typeof GuidesFlooringRoute
  '/guides/hvac-installation': typeof GuidesHvacInstallationRoute
  '/guides/inflated-quote-signs': typeof GuidesInflatedQuoteSignsRoute
  '/guides/kitchen-remodel': typeof GuidesKitchenRemodelRoute
  '/guides/metal-vs-asphalt-roof': typeof GuidesMetalVsAsphaltRoofRoute
  '/guides/roof-replacement': typeof GuidesRoofReplacementRoute
  '/guides/window-replacement': typeof GuidesWindowReplacementRoute
  '/$state/$city/$category': typeof StateCityCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRoute
  '/about': typeof AboutRoute
  '/compare-quotes': typeof CompareQuotesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/estimate': typeof EstimateRoute
  '/insurance-claims': typeof InsuranceClaimsRoute
  '/kitchen-remodel-cost': typeof KitchenRemodelCostRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/quote-analyzer': typeof QuoteAnalyzerRoute
  '/terms': typeof TermsRoute
  '/guides/bathroom-remodel': typeof GuidesBathroomRemodelRoute
  '/guides/flooring': typeof GuidesFlooringRoute
  '/guides/hvac-installation': typeof GuidesHvacInstallationRoute
  '/guides/inflated-quote-signs': typeof GuidesInflatedQuoteSignsRoute
  '/guides/kitchen-remodel': typeof GuidesKitchenRemodelRoute
  '/guides/metal-vs-asphalt-roof': typeof GuidesMetalVsAsphaltRoofRoute
  '/guides/roof-replacement': typeof GuidesRoofReplacementRoute
  '/guides/window-replacement': typeof GuidesWindowReplacementRoute
  '/$state/$city/$category': typeof StateCityCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRoute
  '/about': typeof AboutRoute
  '/compare-quotes': typeof CompareQuotesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/estimate': typeof EstimateRoute
  '/insurance-claims': typeof InsuranceClaimsRoute
  '/kitchen-remodel-cost': typeof KitchenRemodelCostRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/quote-analyzer': typeof QuoteAnalyzerRoute
  '/terms': typeof TermsRoute
  '/guides/bathroom-remodel': typeof GuidesBathroomRemodelRoute
  '/guides/flooring': typeof GuidesFlooringRoute
  '/guides/hvac-installation': typeof GuidesHvacInstallationRoute
  '/guides/inflated-quote-signs': typeof GuidesInflatedQuoteSignsRoute
  '/guides/kitchen-remodel': typeof GuidesKitchenRemodelRoute
  '/guides/metal-vs-asphalt-roof': typeof GuidesMetalVsAsphaltRoofRoute
  '/guides/roof-replacement': typeof GuidesRoofReplacementRoute
  '/guides/window-replacement': typeof GuidesWindowReplacementRoute
  '/$state/$city/$category': typeof StateCityCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectSlug'
    | '/about'
    | '/compare-quotes'
    | '/contact'
    | '/disclaimer'
    | '/estimate'
    | '/insurance-claims'
    | '/kitchen-remodel-cost'
    | '/methodology'
    | '/privacy'
    | '/quote-analyzer'
    | '/terms'
    | '/guides/bathroom-remodel'
    | '/guides/flooring'
    | '/guides/hvac-installation'
    | '/guides/inflated-quote-signs'
    | '/guides/kitchen-remodel'
    | '/guides/metal-vs-asphalt-roof'
    | '/guides/roof-replacement'
    | '/guides/window-replacement'
    | '/$state/$city/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectSlug'
    | '/about'
    | '/compare-quotes'
    | '/contact'
    | '/disclaimer'
    | '/estimate'
    | '/insurance-claims'
    | '/kitchen-remodel-cost'
    | '/methodology'
    | '/privacy'
    | '/quote-analyzer'
    | '/terms'
    | '/guides/bathroom-remodel'
    | '/guides/flooring'
    | '/guides/hvac-installation'
    | '/guides/inflated-quote-signs'
    | '/guides/kitchen-remodel'
    | '/guides/metal-vs-asphalt-roof'
    | '/guides/roof-replacement'
    | '/guides/window-replacement'
    | '/$state/$city/$category'
  id:
    | '__root__'
    | '/'
    | '/$projectSlug'
    | '/about'
    | '/compare-quotes'
    | '/contact'
    | '/disclaimer'
    | '/estimate'
    | '/insurance-claims'
    | '/kitchen-remodel-cost'
    | '/methodology'
    | '/privacy'
    | '/quote-analyzer'
    | '/terms'
    | '/guides/bathroom-remodel'
    | '/guides/flooring'
    | '/guides/hvac-installation'
    | '/guides/inflated-quote-signs'
    | '/guides/kitchen-remodel'
    | '/guides/metal-vs-asphalt-roof'
    | '/guides/roof-replacement'
    | '/guides/window-replacement'
    | '/$state/$city/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  AboutRoute: typeof AboutRoute
  CompareQuotesRoute: typeof CompareQuotesRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EstimateRoute: typeof EstimateRoute
  InsuranceClaimsRoute: typeof InsuranceClaimsRoute
  KitchenRemodelCostRoute: typeof KitchenRemodelCostRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteAnalyzerRoute: typeof QuoteAnalyzerRoute
  TermsRoute: typeof TermsRoute
  GuidesBathroomRemodelRoute: typeof GuidesBathroomRemodelRoute
  GuidesFlooringRoute: typeof GuidesFlooringRoute
  GuidesHvacInstallationRoute: typeof GuidesHvacInstallationRoute
  GuidesInflatedQuoteSignsRoute: typeof GuidesInflatedQuoteSignsRoute
  GuidesKitchenRemodelRoute: typeof GuidesKitchenRemodelRoute
  GuidesMetalVsAsphaltRoofRoute: typeof GuidesMetalVsAsphaltRoofRoute
  GuidesRoofReplacementRoute: typeof GuidesRoofReplacementRoute
  GuidesWindowReplacementRoute: typeof GuidesWindowReplacementRoute
  StateCityCategoryRoute: typeof StateCityCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-analyzer': {
      id: '/quote-analyzer'
      path: '/quote-analyzer'
      fullPath: '/quote-analyzer'
      preLoaderRoute: typeof QuoteAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-remodel-cost': {
      id: '/kitchen-remodel-cost'
      path: '/kitchen-remodel-cost'
      fullPath: '/kitchen-remodel-cost'
      preLoaderRoute: typeof KitchenRemodelCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-claims': {
      id: '/insurance-claims'
      path: '/insurance-claims'
      fullPath: '/insurance-claims'
      preLoaderRoute: typeof InsuranceClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-quotes': {
      id: '/compare-quotes'
      path: '/compare-quotes'
      fullPath: '/compare-quotes'
      preLoaderRoute: typeof CompareQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug': {
      id: '/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$projectSlug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/window-replacement': {
      id: '/guides/window-replacement'
      path: '/guides/window-replacement'
      fullPath: '/guides/window-replacement'
      preLoaderRoute: typeof GuidesWindowReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-replacement': {
      id: '/guides/roof-replacement'
      path: '/guides/roof-replacement'
      fullPath: '/guides/roof-replacement'
      preLoaderRoute: typeof GuidesRoofReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/metal-vs-asphalt-roof': {
      id: '/guides/metal-vs-asphalt-roof'
      path: '/guides/metal-vs-asphalt-roof'
      fullPath: '/guides/metal-vs-asphalt-roof'
      preLoaderRoute: typeof GuidesMetalVsAsphaltRoofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/kitchen-remodel': {
      id: '/guides/kitchen-remodel'
      path: '/guides/kitchen-remodel'
      fullPath: '/guides/kitchen-remodel'
      preLoaderRoute: typeof GuidesKitchenRemodelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/inflated-quote-signs': {
      id: '/guides/inflated-quote-signs'
      path: '/guides/inflated-quote-signs'
      fullPath: '/guides/inflated-quote-signs'
      preLoaderRoute: typeof GuidesInflatedQuoteSignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/hvac-installation': {
      id: '/guides/hvac-installation'
      path: '/guides/hvac-installation'
      fullPath: '/guides/hvac-installation'
      preLoaderRoute: typeof GuidesHvacInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/flooring': {
      id: '/guides/flooring'
      path: '/guides/flooring'
      fullPath: '/guides/flooring'
      preLoaderRoute: typeof GuidesFlooringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/bathroom-remodel': {
      id: '/guides/bathroom-remodel'
      path: '/guides/bathroom-remodel'
      fullPath: '/guides/bathroom-remodel'
      preLoaderRoute: typeof GuidesBathroomRemodelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/$city/$category': {
      id: '/$state/$city/$category'
      path: '/$state/$city/$category'
      fullPath: '/$state/$city/$category'
      preLoaderRoute: typeof StateCityCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  AboutRoute: AboutRoute,
  CompareQuotesRoute: CompareQuotesRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EstimateRoute: EstimateRoute,
  InsuranceClaimsRoute: InsuranceClaimsRoute,
  KitchenRemodelCostRoute: KitchenRemodelCostRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteAnalyzerRoute: QuoteAnalyzerRoute,
  TermsRoute: TermsRoute,
  GuidesBathroomRemodelRoute: GuidesBathroomRemodelRoute,
  GuidesFlooringRoute: GuidesFlooringRoute,
  GuidesHvacInstallationRoute: GuidesHvacInstallationRoute,
  GuidesInflatedQuoteSignsRoute: GuidesInflatedQuoteSignsRoute,
  GuidesKitchenRemodelRoute: GuidesKitchenRemodelRoute,
  GuidesMetalVsAsphaltRoofRoute: GuidesMetalVsAsphaltRoofRoute,
  GuidesRoofReplacementRoute: GuidesRoofReplacementRoute,
  GuidesWindowReplacementRoute: GuidesWindowReplacementRoute,
  StateCityCategoryRoute: StateCityCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
