/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as QuoteAnalyzerRouteImport } from './routes/quote-analyzer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as InsuranceClaimsRouteImport } from './routes/insurance-claims'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareQuotesRouteImport } from './routes/compare-quotes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProjectSlugRouteImport } from './routes/$projectSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as TopicsWindowsRouteImport } from './routes/topics/windows'
import { Route as TopicsRoofRouteImport } from './routes/topics/roof'
import { Route as TopicsQuotesRouteImport } from './routes/topics/quotes'
import { Route as TopicsKitchenRouteImport } from './routes/topics/kitchen'
import { Route as TopicsHvacRouteImport } from './routes/topics/hvac'
import { Route as TopicsFlooringRouteImport } from './routes/topics/flooring'
import { Route as TopicsEnergyRouteImport } from './routes/topics/energy'
import { Route as RIdRouteImport } from './routes/r/$id'
import { Route as LocationsStateRouteImport } from './routes/locations/$state'
import { Route as GuidesWindowReplacementRouteImport } from './routes/guides/window-replacement'
import { Route as GuidesWhatToDoAfterGettingContractorQuotesRouteImport } from './routes/guides/what-to-do-after-getting-contractor-quotes'
import { Route as GuidesSolarPanelCostRouteImport } from './routes/guides/solar-panel-cost'
import { Route as GuidesSmartThermostatInstallationCostRouteImport } from './routes/guides/smart-thermostat-installation-cost'
import { Route as GuidesRoofReplacementTimelineRouteImport } from './routes/guides/roof-replacement-timeline'
import { Route as GuidesRoofReplacementCostByStateRouteImport } from './routes/guides/roof-replacement-cost-by-state'
import { Route as GuidesRoofReplacementCostByCityRouteImport } from './routes/guides/roof-replacement-cost-by-city'
import { Route as GuidesRoofReplacementRouteImport } from './routes/guides/roof-replacement'
import { Route as GuidesRoofQuoteReviewRouteImport } from './routes/guides/roof-quote-review'
import { Route as GuidesRoofPermitsRouteImport } from './routes/guides/roof-permits'
import { Route as GuidesRoofInsuranceClaimsRouteImport } from './routes/guides/roof-insurance-claims'
import { Route as GuidesRoofFinancingRouteImport } from './routes/guides/roof-financing'
import { Route as GuidesQuestionsBeforeSigningRouteImport } from './routes/guides/questions-before-signing'
import { Route as GuidesQuartzVsGraniteCountertopsRouteImport } from './routes/guides/quartz-vs-granite-countertops'
import { Route as GuidesQuartzCountertopCostRouteImport } from './routes/guides/quartz-countertop-cost'
import { Route as GuidesMissingScopeInContractorQuotesRouteImport } from './routes/guides/missing-scope-in-contractor-quotes'
import { Route as GuidesMetalVsAsphaltRoofRouteImport } from './routes/guides/metal-vs-asphalt-roof'
import { Route as GuidesKitchenRemodelRouteImport } from './routes/guides/kitchen-remodel'
import { Route as GuidesKitchenQuoteReviewRouteImport } from './routes/guides/kitchen-quote-review'
import { Route as GuidesIsContractorQuoteFairRouteImport } from './routes/guides/is-contractor-quote-fair'
import { Route as GuidesIs30kEnoughForKitchenRemodelRouteImport } from './routes/guides/is-30k-enough-for-kitchen-remodel'
import { Route as GuidesInflatedQuoteSignsRouteImport } from './routes/guides/inflated-quote-signs'
import { Route as GuidesHvacInstallationRouteImport } from './routes/guides/hvac-installation'
import { Route as GuidesHowToReadAContractorQuoteRouteImport } from './routes/guides/how-to-read-a-contractor-quote'
import { Route as GuidesHowToCompareContractorQuotesRouteImport } from './routes/guides/how-to-compare-contractor-quotes'
import { Route as GuidesFlooringRouteImport } from './routes/guides/flooring'
import { Route as GuidesEvChargerInstallationCostRouteImport } from './routes/guides/ev-charger-installation-cost'
import { Route as GuidesContractorQuoteTooHighRouteImport } from './routes/guides/contractor-quote-too-high'
import { Route as GuidesContractorPaymentSchedulesRouteImport } from './routes/guides/contractor-payment-schedules'
import { Route as GuidesCanInsuranceCoverRoofReplacementRouteImport } from './routes/guides/can-insurance-cover-roof-replacement'
import { Route as GuidesCabinetInstallLaborCostRouteImport } from './routes/guides/cabinet-install-labor-cost'
import { Route as GuidesBathroomRemodelRouteImport } from './routes/guides/bathroom-remodel'
import { Route as GuidesAllowancesAndChangeOrdersRouteImport } from './routes/guides/allowances-and-change-orders'
import { Route as Guides2026KitchenRemodelingCostReportRouteImport } from './routes/guides/2026-kitchen-remodeling-cost-report'
import { Route as StateCityCategoryRouteImport } from './routes/$state/$city/$category'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteAnalyzerRoute = QuoteAnalyzerRouteImport.update({
  id: '/quote-analyzer',
  path: '/quote-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceClaimsRoute = InsuranceClaimsRouteImport.update({
  id: '/insurance-claims',
  path: '/insurance-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareQuotesRoute = CompareQuotesRouteImport.update({
  id: '/compare-quotes',
  path: '/compare-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsWindowsRoute = TopicsWindowsRouteImport.update({
  id: '/topics/windows',
  path: '/topics/windows',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoofRoute = TopicsRoofRouteImport.update({
  id: '/topics/roof',
  path: '/topics/roof',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsQuotesRoute = TopicsQuotesRouteImport.update({
  id: '/topics/quotes',
  path: '/topics/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsKitchenRoute = TopicsKitchenRouteImport.update({
  id: '/topics/kitchen',
  path: '/topics/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsHvacRoute = TopicsHvacRouteImport.update({
  id: '/topics/hvac',
  path: '/topics/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsFlooringRoute = TopicsFlooringRouteImport.update({
  id: '/topics/flooring',
  path: '/topics/flooring',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsEnergyRoute = TopicsEnergyRouteImport.update({
  id: '/topics/energy',
  path: '/topics/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsStateRoute = LocationsStateRouteImport.update({
  id: '/locations/$state',
  path: '/locations/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesWindowReplacementRoute = GuidesWindowReplacementRouteImport.update({
  id: '/guides/window-replacement',
  path: '/guides/window-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesWhatToDoAfterGettingContractorQuotesRoute =
  GuidesWhatToDoAfterGettingContractorQuotesRouteImport.update({
    id: '/guides/what-to-do-after-getting-contractor-quotes',
    path: '/guides/what-to-do-after-getting-contractor-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSolarPanelCostRoute = GuidesSolarPanelCostRouteImport.update({
  id: '/guides/solar-panel-cost',
  path: '/guides/solar-panel-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSmartThermostatInstallationCostRoute =
  GuidesSmartThermostatInstallationCostRouteImport.update({
    id: '/guides/smart-thermostat-installation-cost',
    path: '/guides/smart-thermostat-installation-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoofReplacementTimelineRoute =
  GuidesRoofReplacementTimelineRouteImport.update({
    id: '/guides/roof-replacement-timeline',
    path: '/guides/roof-replacement-timeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoofReplacementCostByStateRoute =
  GuidesRoofReplacementCostByStateRouteImport.update({
    id: '/guides/roof-replacement-cost-by-state',
    path: '/guides/roof-replacement-cost-by-state',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoofReplacementCostByCityRoute =
  GuidesRoofReplacementCostByCityRouteImport.update({
    id: '/guides/roof-replacement-cost-by-city',
    path: '/guides/roof-replacement-cost-by-city',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoofReplacementRoute = GuidesRoofReplacementRouteImport.update({
  id: '/guides/roof-replacement',
  path: '/guides/roof-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoofQuoteReviewRoute = GuidesRoofQuoteReviewRouteImport.update({
  id: '/guides/roof-quote-review',
  path: '/guides/roof-quote-review',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoofPermitsRoute = GuidesRoofPermitsRouteImport.update({
  id: '/guides/roof-permits',
  path: '/guides/roof-permits',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoofInsuranceClaimsRoute =
  GuidesRoofInsuranceClaimsRouteImport.update({
    id: '/guides/roof-insurance-claims',
    path: '/guides/roof-insurance-claims',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoofFinancingRoute = GuidesRoofFinancingRouteImport.update({
  id: '/guides/roof-financing',
  path: '/guides/roof-financing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesQuestionsBeforeSigningRoute =
  GuidesQuestionsBeforeSigningRouteImport.update({
    id: '/guides/questions-before-signing',
    path: '/guides/questions-before-signing',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesQuartzVsGraniteCountertopsRoute =
  GuidesQuartzVsGraniteCountertopsRouteImport.update({
    id: '/guides/quartz-vs-granite-countertops',
    path: '/guides/quartz-vs-granite-countertops',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesQuartzCountertopCostRoute =
  GuidesQuartzCountertopCostRouteImport.update({
    id: '/guides/quartz-countertop-cost',
    path: '/guides/quartz-countertop-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesMissingScopeInContractorQuotesRoute =
  GuidesMissingScopeInContractorQuotesRouteImport.update({
    id: '/guides/missing-scope-in-contractor-quotes',
    path: '/guides/missing-scope-in-contractor-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesMetalVsAsphaltRoofRoute =
  GuidesMetalVsAsphaltRoofRouteImport.update({
    id: '/guides/metal-vs-asphalt-roof',
    path: '/guides/metal-vs-asphalt-roof',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesKitchenRemodelRoute = GuidesKitchenRemodelRouteImport.update({
  id: '/guides/kitchen-remodel',
  path: '/guides/kitchen-remodel',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesKitchenQuoteReviewRoute =
  GuidesKitchenQuoteReviewRouteImport.update({
    id: '/guides/kitchen-quote-review',
    path: '/guides/kitchen-quote-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesIsContractorQuoteFairRoute =
  GuidesIsContractorQuoteFairRouteImport.update({
    id: '/guides/is-contractor-quote-fair',
    path: '/guides/is-contractor-quote-fair',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesIs30kEnoughForKitchenRemodelRoute =
  GuidesIs30kEnoughForKitchenRemodelRouteImport.update({
    id: '/guides/is-30k-enough-for-kitchen-remodel',
    path: '/guides/is-30k-enough-for-kitchen-remodel',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesInflatedQuoteSignsRoute =
  GuidesInflatedQuoteSignsRouteImport.update({
    id: '/guides/inflated-quote-signs',
    path: '/guides/inflated-quote-signs',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHvacInstallationRoute = GuidesHvacInstallationRouteImport.update({
  id: '/guides/hvac-installation',
  path: '/guides/hvac-installation',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHowToReadAContractorQuoteRoute =
  GuidesHowToReadAContractorQuoteRouteImport.update({
    id: '/guides/how-to-read-a-contractor-quote',
    path: '/guides/how-to-read-a-contractor-quote',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowToCompareContractorQuotesRoute =
  GuidesHowToCompareContractorQuotesRouteImport.update({
    id: '/guides/how-to-compare-contractor-quotes',
    path: '/guides/how-to-compare-contractor-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesFlooringRoute = GuidesFlooringRouteImport.update({
  id: '/guides/flooring',
  path: '/guides/flooring',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesEvChargerInstallationCostRoute =
  GuidesEvChargerInstallationCostRouteImport.update({
    id: '/guides/ev-charger-installation-cost',
    path: '/guides/ev-charger-installation-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesContractorQuoteTooHighRoute =
  GuidesContractorQuoteTooHighRouteImport.update({
    id: '/guides/contractor-quote-too-high',
    path: '/guides/contractor-quote-too-high',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesContractorPaymentSchedulesRoute =
  GuidesContractorPaymentSchedulesRouteImport.update({
    id: '/guides/contractor-payment-schedules',
    path: '/guides/contractor-payment-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesCanInsuranceCoverRoofReplacementRoute =
  GuidesCanInsuranceCoverRoofReplacementRouteImport.update({
    id: '/guides/can-insurance-cover-roof-replacement',
    path: '/guides/can-insurance-cover-roof-replacement',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesCabinetInstallLaborCostRoute =
  GuidesCabinetInstallLaborCostRouteImport.update({
    id: '/guides/cabinet-install-labor-cost',
    path: '/guides/cabinet-install-labor-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesBathroomRemodelRoute = GuidesBathroomRemodelRouteImport.update({
  id: '/guides/bathroom-remodel',
  path: '/guides/bathroom-remodel',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAllowancesAndChangeOrdersRoute =
  GuidesAllowancesAndChangeOrdersRouteImport.update({
    id: '/guides/allowances-and-change-orders',
    path: '/guides/allowances-and-change-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const Guides2026KitchenRemodelingCostReportRoute =
  Guides2026KitchenRemodelingCostReportRouteImport.update({
    id: '/guides/2026-kitchen-remodeling-cost-report',
    path: '/guides/2026-kitchen-remodeling-cost-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const StateCityCategoryRoute = StateCityCategoryRouteImport.update({
  id: '/$state/$city/$category',
  path: '/$state/$city/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compare-quotes': typeof CompareQuotesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/estimate': typeof EstimateRoute
  '/insurance-claims': typeof InsuranceClaimsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/quote-analyzer': typeof QuoteAnalyzerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/guides/2026-kitchen-remodeling-cost-report': typeof Guides2026KitchenRemodelingCostReportRoute
  '/guides/allowances-and-change-orders': typeof GuidesAllowancesAndChangeOrdersRoute
  '/guides/bathroom-remodel': typeof GuidesBathroomRemodelRoute
  '/guides/cabinet-install-labor-cost': typeof GuidesCabinetInstallLaborCostRoute
  '/guides/can-insurance-cover-roof-replacement': typeof GuidesCanInsuranceCoverRoofReplacementRoute
  '/guides/contractor-payment-schedules': typeof GuidesContractorPaymentSchedulesRoute
  '/guides/contractor-quote-too-high': typeof GuidesContractorQuoteTooHighRoute
  '/guides/ev-charger-installation-cost': typeof GuidesEvChargerInstallationCostRoute
  '/guides/flooring': typeof GuidesFlooringRoute
  '/guides/how-to-compare-contractor-quotes': typeof GuidesHowToCompareContractorQuotesRoute
  '/guides/how-to-read-a-contractor-quote': typeof GuidesHowToReadAContractorQuoteRoute
  '/guides/hvac-installation': typeof GuidesHvacInstallationRoute
  '/guides/inflated-quote-signs': typeof GuidesInflatedQuoteSignsRoute
  '/guides/is-30k-enough-for-kitchen-remodel': typeof GuidesIs30kEnoughForKitchenRemodelRoute
  '/guides/is-contractor-quote-fair': typeof GuidesIsContractorQuoteFairRoute
  '/guides/kitchen-quote-review': typeof GuidesKitchenQuoteReviewRoute
  '/guides/kitchen-remodel': typeof GuidesKitchenRemodelRoute
  '/guides/metal-vs-asphalt-roof': typeof GuidesMetalVsAsphaltRoofRoute
  '/guides/missing-scope-in-contractor-quotes': typeof GuidesMissingScopeInContractorQuotesRoute
  '/guides/quartz-countertop-cost': typeof GuidesQuartzCountertopCostRoute
  '/guides/quartz-vs-granite-countertops': typeof GuidesQuartzVsGraniteCountertopsRoute
  '/guides/questions-before-signing': typeof GuidesQuestionsBeforeSigningRoute
  '/guides/roof-financing': typeof GuidesRoofFinancingRoute
  '/guides/roof-insurance-claims': typeof GuidesRoofInsuranceClaimsRoute
  '/guides/roof-permits': typeof GuidesRoofPermitsRoute
  '/guides/roof-quote-review': typeof GuidesRoofQuoteReviewRoute
  '/guides/roof-replacement': typeof GuidesRoofReplacementRoute
  '/guides/roof-replacement-cost-by-city': typeof GuidesRoofReplacementCostByCityRoute
  '/guides/roof-replacement-cost-by-state': typeof GuidesRoofReplacementCostByStateRoute
  '/guides/roof-replacement-timeline': typeof GuidesRoofReplacementTimelineRoute
  '/guides/smart-thermostat-installation-cost': typeof GuidesSmartThermostatInstallationCostRoute
  '/guides/solar-panel-cost': typeof GuidesSolarPanelCostRoute
  '/guides/what-to-do-after-getting-contractor-quotes': typeof GuidesWhatToDoAfterGettingContractorQuotesRoute
  '/guides/window-replacement': typeof GuidesWindowReplacementRoute
  '/locations/$state': typeof LocationsStateRoute
  '/r/$id': typeof RIdRoute
  '/topics/energy': typeof TopicsEnergyRoute
  '/topics/flooring': typeof TopicsFlooringRoute
  '/topics/hvac': typeof TopicsHvacRoute
  '/topics/kitchen': typeof TopicsKitchenRoute
  '/topics/quotes': typeof TopicsQuotesRoute
  '/topics/roof': typeof TopicsRoofRoute
  '/topics/windows': typeof TopicsWindowsRoute
  '/guides/': typeof GuidesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/$state/$city/$category': typeof StateCityCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compare-quotes': typeof CompareQuotesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/estimate': typeof EstimateRoute
  '/insurance-claims': typeof InsuranceClaimsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/quote-analyzer': typeof QuoteAnalyzerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/guides/2026-kitchen-remodeling-cost-report': typeof Guides2026KitchenRemodelingCostReportRoute
  '/guides/allowances-and-change-orders': typeof GuidesAllowancesAndChangeOrdersRoute
  '/guides/bathroom-remodel': typeof GuidesBathroomRemodelRoute
  '/guides/cabinet-install-labor-cost': typeof GuidesCabinetInstallLaborCostRoute
  '/guides/can-insurance-cover-roof-replacement': typeof GuidesCanInsuranceCoverRoofReplacementRoute
  '/guides/contractor-payment-schedules': typeof GuidesContractorPaymentSchedulesRoute
  '/guides/contractor-quote-too-high': typeof GuidesContractorQuoteTooHighRoute
  '/guides/ev-charger-installation-cost': typeof GuidesEvChargerInstallationCostRoute
  '/guides/flooring': typeof GuidesFlooringRoute
  '/guides/how-to-compare-contractor-quotes': typeof GuidesHowToCompareContractorQuotesRoute
  '/guides/how-to-read-a-contractor-quote': typeof GuidesHowToReadAContractorQuoteRoute
  '/guides/hvac-installation': typeof GuidesHvacInstallationRoute
  '/guides/inflated-quote-signs': typeof GuidesInflatedQuoteSignsRoute
  '/guides/is-30k-enough-for-kitchen-remodel': typeof GuidesIs30kEnoughForKitchenRemodelRoute
  '/guides/is-contractor-quote-fair': typeof GuidesIsContractorQuoteFairRoute
  '/guides/kitchen-quote-review': typeof GuidesKitchenQuoteReviewRoute
  '/guides/kitchen-remodel': typeof GuidesKitchenRemodelRoute
  '/guides/metal-vs-asphalt-roof': typeof GuidesMetalVsAsphaltRoofRoute
  '/guides/missing-scope-in-contractor-quotes': typeof GuidesMissingScopeInContractorQuotesRoute
  '/guides/quartz-countertop-cost': typeof GuidesQuartzCountertopCostRoute
  '/guides/quartz-vs-granite-countertops': typeof GuidesQuartzVsGraniteCountertopsRoute
  '/guides/questions-before-signing': typeof GuidesQuestionsBeforeSigningRoute
  '/guides/roof-financing': typeof GuidesRoofFinancingRoute
  '/guides/roof-insurance-claims': typeof GuidesRoofInsuranceClaimsRoute
  '/guides/roof-permits': typeof GuidesRoofPermitsRoute
  '/guides/roof-quote-review': typeof GuidesRoofQuoteReviewRoute
  '/guides/roof-replacement': typeof GuidesRoofReplacementRoute
  '/guides/roof-replacement-cost-by-city': typeof GuidesRoofReplacementCostByCityRoute
  '/guides/roof-replacement-cost-by-state': typeof GuidesRoofReplacementCostByStateRoute
  '/guides/roof-replacement-timeline': typeof GuidesRoofReplacementTimelineRoute
  '/guides/smart-thermostat-installation-cost': typeof GuidesSmartThermostatInstallationCostRoute
  '/guides/solar-panel-cost': typeof GuidesSolarPanelCostRoute
  '/guides/what-to-do-after-getting-contractor-quotes': typeof GuidesWhatToDoAfterGettingContractorQuotesRoute
  '/guides/window-replacement': typeof GuidesWindowReplacementRoute
  '/locations/$state': typeof LocationsStateRoute
  '/r/$id': typeof RIdRoute
  '/topics/energy': typeof TopicsEnergyRoute
  '/topics/flooring': typeof TopicsFlooringRoute
  '/topics/hvac': typeof TopicsHvacRoute
  '/topics/kitchen': typeof TopicsKitchenRoute
  '/topics/quotes': typeof TopicsQuotesRoute
  '/topics/roof': typeof TopicsRoofRoute
  '/topics/windows': typeof TopicsWindowsRoute
  '/guides': typeof GuidesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/$state/$city/$category': typeof StateCityCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/compare-quotes': typeof CompareQuotesRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/estimate': typeof EstimateRoute
  '/insurance-claims': typeof InsuranceClaimsRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/quote-analyzer': typeof QuoteAnalyzerRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/guides/2026-kitchen-remodeling-cost-report': typeof Guides2026KitchenRemodelingCostReportRoute
  '/guides/allowances-and-change-orders': typeof GuidesAllowancesAndChangeOrdersRoute
  '/guides/bathroom-remodel': typeof GuidesBathroomRemodelRoute
  '/guides/cabinet-install-labor-cost': typeof GuidesCabinetInstallLaborCostRoute
  '/guides/can-insurance-cover-roof-replacement': typeof GuidesCanInsuranceCoverRoofReplacementRoute
  '/guides/contractor-payment-schedules': typeof GuidesContractorPaymentSchedulesRoute
  '/guides/contractor-quote-too-high': typeof GuidesContractorQuoteTooHighRoute
  '/guides/ev-charger-installation-cost': typeof GuidesEvChargerInstallationCostRoute
  '/guides/flooring': typeof GuidesFlooringRoute
  '/guides/how-to-compare-contractor-quotes': typeof GuidesHowToCompareContractorQuotesRoute
  '/guides/how-to-read-a-contractor-quote': typeof GuidesHowToReadAContractorQuoteRoute
  '/guides/hvac-installation': typeof GuidesHvacInstallationRoute
  '/guides/inflated-quote-signs': typeof GuidesInflatedQuoteSignsRoute
  '/guides/is-30k-enough-for-kitchen-remodel': typeof GuidesIs30kEnoughForKitchenRemodelRoute
  '/guides/is-contractor-quote-fair': typeof GuidesIsContractorQuoteFairRoute
  '/guides/kitchen-quote-review': typeof GuidesKitchenQuoteReviewRoute
  '/guides/kitchen-remodel': typeof GuidesKitchenRemodelRoute
  '/guides/metal-vs-asphalt-roof': typeof GuidesMetalVsAsphaltRoofRoute
  '/guides/missing-scope-in-contractor-quotes': typeof GuidesMissingScopeInContractorQuotesRoute
  '/guides/quartz-countertop-cost': typeof GuidesQuartzCountertopCostRoute
  '/guides/quartz-vs-granite-countertops': typeof GuidesQuartzVsGraniteCountertopsRoute
  '/guides/questions-before-signing': typeof GuidesQuestionsBeforeSigningRoute
  '/guides/roof-financing': typeof GuidesRoofFinancingRoute
  '/guides/roof-insurance-claims': typeof GuidesRoofInsuranceClaimsRoute
  '/guides/roof-permits': typeof GuidesRoofPermitsRoute
  '/guides/roof-quote-review': typeof GuidesRoofQuoteReviewRoute
  '/guides/roof-replacement': typeof GuidesRoofReplacementRoute
  '/guides/roof-replacement-cost-by-city': typeof GuidesRoofReplacementCostByCityRoute
  '/guides/roof-replacement-cost-by-state': typeof GuidesRoofReplacementCostByStateRoute
  '/guides/roof-replacement-timeline': typeof GuidesRoofReplacementTimelineRoute
  '/guides/smart-thermostat-installation-cost': typeof GuidesSmartThermostatInstallationCostRoute
  '/guides/solar-panel-cost': typeof GuidesSolarPanelCostRoute
  '/guides/what-to-do-after-getting-contractor-quotes': typeof GuidesWhatToDoAfterGettingContractorQuotesRoute
  '/guides/window-replacement': typeof GuidesWindowReplacementRoute
  '/locations/$state': typeof LocationsStateRoute
  '/r/$id': typeof RIdRoute
  '/topics/energy': typeof TopicsEnergyRoute
  '/topics/flooring': typeof TopicsFlooringRoute
  '/topics/hvac': typeof TopicsHvacRoute
  '/topics/kitchen': typeof TopicsKitchenRoute
  '/topics/quotes': typeof TopicsQuotesRoute
  '/topics/roof': typeof TopicsRoofRoute
  '/topics/windows': typeof TopicsWindowsRoute
  '/guides/': typeof GuidesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/$state/$city/$category': typeof StateCityCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectSlug'
    | '/about'
    | '/admin'
    | '/compare-quotes'
    | '/contact'
    | '/disclaimer'
    | '/estimate'
    | '/insurance-claims'
    | '/methodology'
    | '/privacy'
    | '/quote-analyzer'
    | '/robots.txt'
    | '/terms'
    | '/guides/2026-kitchen-remodeling-cost-report'
    | '/guides/allowances-and-change-orders'
    | '/guides/bathroom-remodel'
    | '/guides/cabinet-install-labor-cost'
    | '/guides/can-insurance-cover-roof-replacement'
    | '/guides/contractor-payment-schedules'
    | '/guides/contractor-quote-too-high'
    | '/guides/ev-charger-installation-cost'
    | '/guides/flooring'
    | '/guides/how-to-compare-contractor-quotes'
    | '/guides/how-to-read-a-contractor-quote'
    | '/guides/hvac-installation'
    | '/guides/inflated-quote-signs'
    | '/guides/is-30k-enough-for-kitchen-remodel'
    | '/guides/is-contractor-quote-fair'
    | '/guides/kitchen-quote-review'
    | '/guides/kitchen-remodel'
    | '/guides/metal-vs-asphalt-roof'
    | '/guides/missing-scope-in-contractor-quotes'
    | '/guides/quartz-countertop-cost'
    | '/guides/quartz-vs-granite-countertops'
    | '/guides/questions-before-signing'
    | '/guides/roof-financing'
    | '/guides/roof-insurance-claims'
    | '/guides/roof-permits'
    | '/guides/roof-quote-review'
    | '/guides/roof-replacement'
    | '/guides/roof-replacement-cost-by-city'
    | '/guides/roof-replacement-cost-by-state'
    | '/guides/roof-replacement-timeline'
    | '/guides/smart-thermostat-installation-cost'
    | '/guides/solar-panel-cost'
    | '/guides/what-to-do-after-getting-contractor-quotes'
    | '/guides/window-replacement'
    | '/locations/$state'
    | '/r/$id'
    | '/topics/energy'
    | '/topics/flooring'
    | '/topics/hvac'
    | '/topics/kitchen'
    | '/topics/quotes'
    | '/topics/roof'
    | '/topics/windows'
    | '/guides/'
    | '/locations/'
    | '/$state/$city/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectSlug'
    | '/about'
    | '/admin'
    | '/compare-quotes'
    | '/contact'
    | '/disclaimer'
    | '/estimate'
    | '/insurance-claims'
    | '/methodology'
    | '/privacy'
    | '/quote-analyzer'
    | '/robots.txt'
    | '/terms'
    | '/guides/2026-kitchen-remodeling-cost-report'
    | '/guides/allowances-and-change-orders'
    | '/guides/bathroom-remodel'
    | '/guides/cabinet-install-labor-cost'
    | '/guides/can-insurance-cover-roof-replacement'
    | '/guides/contractor-payment-schedules'
    | '/guides/contractor-quote-too-high'
    | '/guides/ev-charger-installation-cost'
    | '/guides/flooring'
    | '/guides/how-to-compare-contractor-quotes'
    | '/guides/how-to-read-a-contractor-quote'
    | '/guides/hvac-installation'
    | '/guides/inflated-quote-signs'
    | '/guides/is-30k-enough-for-kitchen-remodel'
    | '/guides/is-contractor-quote-fair'
    | '/guides/kitchen-quote-review'
    | '/guides/kitchen-remodel'
    | '/guides/metal-vs-asphalt-roof'
    | '/guides/missing-scope-in-contractor-quotes'
    | '/guides/quartz-countertop-cost'
    | '/guides/quartz-vs-granite-countertops'
    | '/guides/questions-before-signing'
    | '/guides/roof-financing'
    | '/guides/roof-insurance-claims'
    | '/guides/roof-permits'
    | '/guides/roof-quote-review'
    | '/guides/roof-replacement'
    | '/guides/roof-replacement-cost-by-city'
    | '/guides/roof-replacement-cost-by-state'
    | '/guides/roof-replacement-timeline'
    | '/guides/smart-thermostat-installation-cost'
    | '/guides/solar-panel-cost'
    | '/guides/what-to-do-after-getting-contractor-quotes'
    | '/guides/window-replacement'
    | '/locations/$state'
    | '/r/$id'
    | '/topics/energy'
    | '/topics/flooring'
    | '/topics/hvac'
    | '/topics/kitchen'
    | '/topics/quotes'
    | '/topics/roof'
    | '/topics/windows'
    | '/guides'
    | '/locations'
    | '/$state/$city/$category'
  id:
    | '__root__'
    | '/'
    | '/$projectSlug'
    | '/about'
    | '/admin'
    | '/compare-quotes'
    | '/contact'
    | '/disclaimer'
    | '/estimate'
    | '/insurance-claims'
    | '/methodology'
    | '/privacy'
    | '/quote-analyzer'
    | '/robots.txt'
    | '/terms'
    | '/guides/2026-kitchen-remodeling-cost-report'
    | '/guides/allowances-and-change-orders'
    | '/guides/bathroom-remodel'
    | '/guides/cabinet-install-labor-cost'
    | '/guides/can-insurance-cover-roof-replacement'
    | '/guides/contractor-payment-schedules'
    | '/guides/contractor-quote-too-high'
    | '/guides/ev-charger-installation-cost'
    | '/guides/flooring'
    | '/guides/how-to-compare-contractor-quotes'
    | '/guides/how-to-read-a-contractor-quote'
    | '/guides/hvac-installation'
    | '/guides/inflated-quote-signs'
    | '/guides/is-30k-enough-for-kitchen-remodel'
    | '/guides/is-contractor-quote-fair'
    | '/guides/kitchen-quote-review'
    | '/guides/kitchen-remodel'
    | '/guides/metal-vs-asphalt-roof'
    | '/guides/missing-scope-in-contractor-quotes'
    | '/guides/quartz-countertop-cost'
    | '/guides/quartz-vs-granite-countertops'
    | '/guides/questions-before-signing'
    | '/guides/roof-financing'
    | '/guides/roof-insurance-claims'
    | '/guides/roof-permits'
    | '/guides/roof-quote-review'
    | '/guides/roof-replacement'
    | '/guides/roof-replacement-cost-by-city'
    | '/guides/roof-replacement-cost-by-state'
    | '/guides/roof-replacement-timeline'
    | '/guides/smart-thermostat-installation-cost'
    | '/guides/solar-panel-cost'
    | '/guides/what-to-do-after-getting-contractor-quotes'
    | '/guides/window-replacement'
    | '/locations/$state'
    | '/r/$id'
    | '/topics/energy'
    | '/topics/flooring'
    | '/topics/hvac'
    | '/topics/kitchen'
    | '/topics/quotes'
    | '/topics/roof'
    | '/topics/windows'
    | '/guides/'
    | '/locations/'
    | '/$state/$city/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CompareQuotesRoute: typeof CompareQuotesRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EstimateRoute: typeof EstimateRoute
  InsuranceClaimsRoute: typeof InsuranceClaimsRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteAnalyzerRoute: typeof QuoteAnalyzerRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  TermsRoute: typeof TermsRoute
  Guides2026KitchenRemodelingCostReportRoute: typeof Guides2026KitchenRemodelingCostReportRoute
  GuidesAllowancesAndChangeOrdersRoute: typeof GuidesAllowancesAndChangeOrdersRoute
  GuidesBathroomRemodelRoute: typeof GuidesBathroomRemodelRoute
  GuidesCabinetInstallLaborCostRoute: typeof GuidesCabinetInstallLaborCostRoute
  GuidesCanInsuranceCoverRoofReplacementRoute: typeof GuidesCanInsuranceCoverRoofReplacementRoute
  GuidesContractorPaymentSchedulesRoute: typeof GuidesContractorPaymentSchedulesRoute
  GuidesContractorQuoteTooHighRoute: typeof GuidesContractorQuoteTooHighRoute
  GuidesEvChargerInstallationCostRoute: typeof GuidesEvChargerInstallationCostRoute
  GuidesFlooringRoute: typeof GuidesFlooringRoute
  GuidesHowToCompareContractorQuotesRoute: typeof GuidesHowToCompareContractorQuotesRoute
  GuidesHowToReadAContractorQuoteRoute: typeof GuidesHowToReadAContractorQuoteRoute
  GuidesHvacInstallationRoute: typeof GuidesHvacInstallationRoute
  GuidesInflatedQuoteSignsRoute: typeof GuidesInflatedQuoteSignsRoute
  GuidesIs30kEnoughForKitchenRemodelRoute: typeof GuidesIs30kEnoughForKitchenRemodelRoute
  GuidesIsContractorQuoteFairRoute: typeof GuidesIsContractorQuoteFairRoute
  GuidesKitchenQuoteReviewRoute: typeof GuidesKitchenQuoteReviewRoute
  GuidesKitchenRemodelRoute: typeof GuidesKitchenRemodelRoute
  GuidesMetalVsAsphaltRoofRoute: typeof GuidesMetalVsAsphaltRoofRoute
  GuidesMissingScopeInContractorQuotesRoute: typeof GuidesMissingScopeInContractorQuotesRoute
  GuidesQuartzCountertopCostRoute: typeof GuidesQuartzCountertopCostRoute
  GuidesQuartzVsGraniteCountertopsRoute: typeof GuidesQuartzVsGraniteCountertopsRoute
  GuidesQuestionsBeforeSigningRoute: typeof GuidesQuestionsBeforeSigningRoute
  GuidesRoofFinancingRoute: typeof GuidesRoofFinancingRoute
  GuidesRoofInsuranceClaimsRoute: typeof GuidesRoofInsuranceClaimsRoute
  GuidesRoofPermitsRoute: typeof GuidesRoofPermitsRoute
  GuidesRoofQuoteReviewRoute: typeof GuidesRoofQuoteReviewRoute
  GuidesRoofReplacementRoute: typeof GuidesRoofReplacementRoute
  GuidesRoofReplacementCostByCityRoute: typeof GuidesRoofReplacementCostByCityRoute
  GuidesRoofReplacementCostByStateRoute: typeof GuidesRoofReplacementCostByStateRoute
  GuidesRoofReplacementTimelineRoute: typeof GuidesRoofReplacementTimelineRoute
  GuidesSmartThermostatInstallationCostRoute: typeof GuidesSmartThermostatInstallationCostRoute
  GuidesSolarPanelCostRoute: typeof GuidesSolarPanelCostRoute
  GuidesWhatToDoAfterGettingContractorQuotesRoute: typeof GuidesWhatToDoAfterGettingContractorQuotesRoute
  GuidesWindowReplacementRoute: typeof GuidesWindowReplacementRoute
  LocationsStateRoute: typeof LocationsStateRoute
  RIdRoute: typeof RIdRoute
  TopicsEnergyRoute: typeof TopicsEnergyRoute
  TopicsFlooringRoute: typeof TopicsFlooringRoute
  TopicsHvacRoute: typeof TopicsHvacRoute
  TopicsKitchenRoute: typeof TopicsKitchenRoute
  TopicsQuotesRoute: typeof TopicsQuotesRoute
  TopicsRoofRoute: typeof TopicsRoofRoute
  TopicsWindowsRoute: typeof TopicsWindowsRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  StateCityCategoryRoute: typeof StateCityCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-analyzer': {
      id: '/quote-analyzer'
      path: '/quote-analyzer'
      fullPath: '/quote-analyzer'
      preLoaderRoute: typeof QuoteAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-claims': {
      id: '/insurance-claims'
      path: '/insurance-claims'
      fullPath: '/insurance-claims'
      preLoaderRoute: typeof InsuranceClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-quotes': {
      id: '/compare-quotes'
      path: '/compare-quotes'
      fullPath: '/compare-quotes'
      preLoaderRoute: typeof CompareQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug': {
      id: '/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$projectSlug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/windows': {
      id: '/topics/windows'
      path: '/topics/windows'
      fullPath: '/topics/windows'
      preLoaderRoute: typeof TopicsWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/roof': {
      id: '/topics/roof'
      path: '/topics/roof'
      fullPath: '/topics/roof'
      preLoaderRoute: typeof TopicsRoofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/quotes': {
      id: '/topics/quotes'
      path: '/topics/quotes'
      fullPath: '/topics/quotes'
      preLoaderRoute: typeof TopicsQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/kitchen': {
      id: '/topics/kitchen'
      path: '/topics/kitchen'
      fullPath: '/topics/kitchen'
      preLoaderRoute: typeof TopicsKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/hvac': {
      id: '/topics/hvac'
      path: '/topics/hvac'
      fullPath: '/topics/hvac'
      preLoaderRoute: typeof TopicsHvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/flooring': {
      id: '/topics/flooring'
      path: '/topics/flooring'
      fullPath: '/topics/flooring'
      preLoaderRoute: typeof TopicsFlooringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/energy': {
      id: '/topics/energy'
      path: '/topics/energy'
      fullPath: '/topics/energy'
      preLoaderRoute: typeof TopicsEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$state': {
      id: '/locations/$state'
      path: '/locations/$state'
      fullPath: '/locations/$state'
      preLoaderRoute: typeof LocationsStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/window-replacement': {
      id: '/guides/window-replacement'
      path: '/guides/window-replacement'
      fullPath: '/guides/window-replacement'
      preLoaderRoute: typeof GuidesWindowReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/what-to-do-after-getting-contractor-quotes': {
      id: '/guides/what-to-do-after-getting-contractor-quotes'
      path: '/guides/what-to-do-after-getting-contractor-quotes'
      fullPath: '/guides/what-to-do-after-getting-contractor-quotes'
      preLoaderRoute: typeof GuidesWhatToDoAfterGettingContractorQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/solar-panel-cost': {
      id: '/guides/solar-panel-cost'
      path: '/guides/solar-panel-cost'
      fullPath: '/guides/solar-panel-cost'
      preLoaderRoute: typeof GuidesSolarPanelCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/smart-thermostat-installation-cost': {
      id: '/guides/smart-thermostat-installation-cost'
      path: '/guides/smart-thermostat-installation-cost'
      fullPath: '/guides/smart-thermostat-installation-cost'
      preLoaderRoute: typeof GuidesSmartThermostatInstallationCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-replacement-timeline': {
      id: '/guides/roof-replacement-timeline'
      path: '/guides/roof-replacement-timeline'
      fullPath: '/guides/roof-replacement-timeline'
      preLoaderRoute: typeof GuidesRoofReplacementTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-replacement-cost-by-state': {
      id: '/guides/roof-replacement-cost-by-state'
      path: '/guides/roof-replacement-cost-by-state'
      fullPath: '/guides/roof-replacement-cost-by-state'
      preLoaderRoute: typeof GuidesRoofReplacementCostByStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-replacement-cost-by-city': {
      id: '/guides/roof-replacement-cost-by-city'
      path: '/guides/roof-replacement-cost-by-city'
      fullPath: '/guides/roof-replacement-cost-by-city'
      preLoaderRoute: typeof GuidesRoofReplacementCostByCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-replacement': {
      id: '/guides/roof-replacement'
      path: '/guides/roof-replacement'
      fullPath: '/guides/roof-replacement'
      preLoaderRoute: typeof GuidesRoofReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-quote-review': {
      id: '/guides/roof-quote-review'
      path: '/guides/roof-quote-review'
      fullPath: '/guides/roof-quote-review'
      preLoaderRoute: typeof GuidesRoofQuoteReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-permits': {
      id: '/guides/roof-permits'
      path: '/guides/roof-permits'
      fullPath: '/guides/roof-permits'
      preLoaderRoute: typeof GuidesRoofPermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-insurance-claims': {
      id: '/guides/roof-insurance-claims'
      path: '/guides/roof-insurance-claims'
      fullPath: '/guides/roof-insurance-claims'
      preLoaderRoute: typeof GuidesRoofInsuranceClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/roof-financing': {
      id: '/guides/roof-financing'
      path: '/guides/roof-financing'
      fullPath: '/guides/roof-financing'
      preLoaderRoute: typeof GuidesRoofFinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/questions-before-signing': {
      id: '/guides/questions-before-signing'
      path: '/guides/questions-before-signing'
      fullPath: '/guides/questions-before-signing'
      preLoaderRoute: typeof GuidesQuestionsBeforeSigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/quartz-vs-granite-countertops': {
      id: '/guides/quartz-vs-granite-countertops'
      path: '/guides/quartz-vs-granite-countertops'
      fullPath: '/guides/quartz-vs-granite-countertops'
      preLoaderRoute: typeof GuidesQuartzVsGraniteCountertopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/quartz-countertop-cost': {
      id: '/guides/quartz-countertop-cost'
      path: '/guides/quartz-countertop-cost'
      fullPath: '/guides/quartz-countertop-cost'
      preLoaderRoute: typeof GuidesQuartzCountertopCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/missing-scope-in-contractor-quotes': {
      id: '/guides/missing-scope-in-contractor-quotes'
      path: '/guides/missing-scope-in-contractor-quotes'
      fullPath: '/guides/missing-scope-in-contractor-quotes'
      preLoaderRoute: typeof GuidesMissingScopeInContractorQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/metal-vs-asphalt-roof': {
      id: '/guides/metal-vs-asphalt-roof'
      path: '/guides/metal-vs-asphalt-roof'
      fullPath: '/guides/metal-vs-asphalt-roof'
      preLoaderRoute: typeof GuidesMetalVsAsphaltRoofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/kitchen-remodel': {
      id: '/guides/kitchen-remodel'
      path: '/guides/kitchen-remodel'
      fullPath: '/guides/kitchen-remodel'
      preLoaderRoute: typeof GuidesKitchenRemodelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/kitchen-quote-review': {
      id: '/guides/kitchen-quote-review'
      path: '/guides/kitchen-quote-review'
      fullPath: '/guides/kitchen-quote-review'
      preLoaderRoute: typeof GuidesKitchenQuoteReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/is-contractor-quote-fair': {
      id: '/guides/is-contractor-quote-fair'
      path: '/guides/is-contractor-quote-fair'
      fullPath: '/guides/is-contractor-quote-fair'
      preLoaderRoute: typeof GuidesIsContractorQuoteFairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/is-30k-enough-for-kitchen-remodel': {
      id: '/guides/is-30k-enough-for-kitchen-remodel'
      path: '/guides/is-30k-enough-for-kitchen-remodel'
      fullPath: '/guides/is-30k-enough-for-kitchen-remodel'
      preLoaderRoute: typeof GuidesIs30kEnoughForKitchenRemodelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/inflated-quote-signs': {
      id: '/guides/inflated-quote-signs'
      path: '/guides/inflated-quote-signs'
      fullPath: '/guides/inflated-quote-signs'
      preLoaderRoute: typeof GuidesInflatedQuoteSignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/hvac-installation': {
      id: '/guides/hvac-installation'
      path: '/guides/hvac-installation'
      fullPath: '/guides/hvac-installation'
      preLoaderRoute: typeof GuidesHvacInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-read-a-contractor-quote': {
      id: '/guides/how-to-read-a-contractor-quote'
      path: '/guides/how-to-read-a-contractor-quote'
      fullPath: '/guides/how-to-read-a-contractor-quote'
      preLoaderRoute: typeof GuidesHowToReadAContractorQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-compare-contractor-quotes': {
      id: '/guides/how-to-compare-contractor-quotes'
      path: '/guides/how-to-compare-contractor-quotes'
      fullPath: '/guides/how-to-compare-contractor-quotes'
      preLoaderRoute: typeof GuidesHowToCompareContractorQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/flooring': {
      id: '/guides/flooring'
      path: '/guides/flooring'
      fullPath: '/guides/flooring'
      preLoaderRoute: typeof GuidesFlooringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/ev-charger-installation-cost': {
      id: '/guides/ev-charger-installation-cost'
      path: '/guides/ev-charger-installation-cost'
      fullPath: '/guides/ev-charger-installation-cost'
      preLoaderRoute: typeof GuidesEvChargerInstallationCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/contractor-quote-too-high': {
      id: '/guides/contractor-quote-too-high'
      path: '/guides/contractor-quote-too-high'
      fullPath: '/guides/contractor-quote-too-high'
      preLoaderRoute: typeof GuidesContractorQuoteTooHighRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/contractor-payment-schedules': {
      id: '/guides/contractor-payment-schedules'
      path: '/guides/contractor-payment-schedules'
      fullPath: '/guides/contractor-payment-schedules'
      preLoaderRoute: typeof GuidesContractorPaymentSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/can-insurance-cover-roof-replacement': {
      id: '/guides/can-insurance-cover-roof-replacement'
      path: '/guides/can-insurance-cover-roof-replacement'
      fullPath: '/guides/can-insurance-cover-roof-replacement'
      preLoaderRoute: typeof GuidesCanInsuranceCoverRoofReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/cabinet-install-labor-cost': {
      id: '/guides/cabinet-install-labor-cost'
      path: '/guides/cabinet-install-labor-cost'
      fullPath: '/guides/cabinet-install-labor-cost'
      preLoaderRoute: typeof GuidesCabinetInstallLaborCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/bathroom-remodel': {
      id: '/guides/bathroom-remodel'
      path: '/guides/bathroom-remodel'
      fullPath: '/guides/bathroom-remodel'
      preLoaderRoute: typeof GuidesBathroomRemodelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/allowances-and-change-orders': {
      id: '/guides/allowances-and-change-orders'
      path: '/guides/allowances-and-change-orders'
      fullPath: '/guides/allowances-and-change-orders'
      preLoaderRoute: typeof GuidesAllowancesAndChangeOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/2026-kitchen-remodeling-cost-report': {
      id: '/guides/2026-kitchen-remodeling-cost-report'
      path: '/guides/2026-kitchen-remodeling-cost-report'
      fullPath: '/guides/2026-kitchen-remodeling-cost-report'
      preLoaderRoute: typeof Guides2026KitchenRemodelingCostReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$state/$city/$category': {
      id: '/$state/$city/$category'
      path: '/$state/$city/$category'
      fullPath: '/$state/$city/$category'
      preLoaderRoute: typeof StateCityCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CompareQuotesRoute: CompareQuotesRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EstimateRoute: EstimateRoute,
  InsuranceClaimsRoute: InsuranceClaimsRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteAnalyzerRoute: QuoteAnalyzerRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  TermsRoute: TermsRoute,
  Guides2026KitchenRemodelingCostReportRoute:
    Guides2026KitchenRemodelingCostReportRoute,
  GuidesAllowancesAndChangeOrdersRoute: GuidesAllowancesAndChangeOrdersRoute,
  GuidesBathroomRemodelRoute: GuidesBathroomRemodelRoute,
  GuidesCabinetInstallLaborCostRoute: GuidesCabinetInstallLaborCostRoute,
  GuidesCanInsuranceCoverRoofReplacementRoute:
    GuidesCanInsuranceCoverRoofReplacementRoute,
  GuidesContractorPaymentSchedulesRoute: GuidesContractorPaymentSchedulesRoute,
  GuidesContractorQuoteTooHighRoute: GuidesContractorQuoteTooHighRoute,
  GuidesEvChargerInstallationCostRoute: GuidesEvChargerInstallationCostRoute,
  GuidesFlooringRoute: GuidesFlooringRoute,
  GuidesHowToCompareContractorQuotesRoute:
    GuidesHowToCompareContractorQuotesRoute,
  GuidesHowToReadAContractorQuoteRoute: GuidesHowToReadAContractorQuoteRoute,
  GuidesHvacInstallationRoute: GuidesHvacInstallationRoute,
  GuidesInflatedQuoteSignsRoute: GuidesInflatedQuoteSignsRoute,
  GuidesIs30kEnoughForKitchenRemodelRoute:
    GuidesIs30kEnoughForKitchenRemodelRoute,
  GuidesIsContractorQuoteFairRoute: GuidesIsContractorQuoteFairRoute,
  GuidesKitchenQuoteReviewRoute: GuidesKitchenQuoteReviewRoute,
  GuidesKitchenRemodelRoute: GuidesKitchenRemodelRoute,
  GuidesMetalVsAsphaltRoofRoute: GuidesMetalVsAsphaltRoofRoute,
  GuidesMissingScopeInContractorQuotesRoute:
    GuidesMissingScopeInContractorQuotesRoute,
  GuidesQuartzCountertopCostRoute: GuidesQuartzCountertopCostRoute,
  GuidesQuartzVsGraniteCountertopsRoute: GuidesQuartzVsGraniteCountertopsRoute,
  GuidesQuestionsBeforeSigningRoute: GuidesQuestionsBeforeSigningRoute,
  GuidesRoofFinancingRoute: GuidesRoofFinancingRoute,
  GuidesRoofInsuranceClaimsRoute: GuidesRoofInsuranceClaimsRoute,
  GuidesRoofPermitsRoute: GuidesRoofPermitsRoute,
  GuidesRoofQuoteReviewRoute: GuidesRoofQuoteReviewRoute,
  GuidesRoofReplacementRoute: GuidesRoofReplacementRoute,
  GuidesRoofReplacementCostByCityRoute: GuidesRoofReplacementCostByCityRoute,
  GuidesRoofReplacementCostByStateRoute: GuidesRoofReplacementCostByStateRoute,
  GuidesRoofReplacementTimelineRoute: GuidesRoofReplacementTimelineRoute,
  GuidesSmartThermostatInstallationCostRoute:
    GuidesSmartThermostatInstallationCostRoute,
  GuidesSolarPanelCostRoute: GuidesSolarPanelCostRoute,
  GuidesWhatToDoAfterGettingContractorQuotesRoute:
    GuidesWhatToDoAfterGettingContractorQuotesRoute,
  GuidesWindowReplacementRoute: GuidesWindowReplacementRoute,
  LocationsStateRoute: LocationsStateRoute,
  RIdRoute: RIdRoute,
  TopicsEnergyRoute: TopicsEnergyRoute,
  TopicsFlooringRoute: TopicsFlooringRoute,
  TopicsHvacRoute: TopicsHvacRoute,
  TopicsKitchenRoute: TopicsKitchenRoute,
  TopicsQuotesRoute: TopicsQuotesRoute,
  TopicsRoofRoute: TopicsRoofRoute,
  TopicsWindowsRoute: TopicsWindowsRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  StateCityCategoryRoute: StateCityCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
